# Generated by Django 6.0.3 on 2026-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_manager', '0003_pharmacistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacistprofile',
            name='employee_id',
            field=models.CharField(help_text='Unique staff identification number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionticket',
            name='phone_number',
            field=models.CharField(blank=True, help_text='For status notifications via WhatsApp', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionticket',
            name='queue_number',
            field=models.IntegerField(help_text='Sequential number displayed to customers', unique=True),
        ),
    ]
